In [1]:
import numpy as np

Y_predicted = np.array([1,1,0,0,1])
Y_true = np.array([0.30,0.7,1,0,0.5])

In [2]:
def mae (Y_true,Y_predicted):
    total_error = 0
    for yt, yp in zip(Y_true, Y_predicted):
        total_error += abs(yt - yp)
    print("Total Error:",total_error)


    mae = total_error / len(Y_true)
    print("MAE:",mae)
    return mae

In [3]:
mae(Y_true,Y_predicted)

Total Error: 2.5
MAE: 0.5


0.5

In [4]:
Y_predicted - Y_true   #this is give you a real differnce

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [5]:
np.abs(Y_predicted - Y_true)     #if we want absolute diff. we can do this

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(Y_predicted - Y_true)) # if we want a mean of absolute error then we do this

0.5

In [7]:
np.sum(np.abs(Y_predicted - Y_true)) # this will give total error

2.5

In [8]:
eplison = 1e-15

In [9]:
Y_predicted_new = [max(i,eplison) for i in Y_predicted]
Y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [10]:
Y_predicted_new = [min(i,1-eplison) for i in Y_predicted_new]
Y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [11]:
Y_predicted_new = np.array(Y_predicted_new)
np.log(Y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [12]:
-np.mean(Y_true*np.log(Y_predicted_new)+(1-Y_true)*np.log(1-Y_predicted_new))

17.2696280766844

In [13]:
def log_loss(Y_true,Y_predicted):
    eplison = 1e-15
    Y_predicted_new = [max(i,eplison) for i in Y_predicted]
    Y_predicted_new = [min(i,1-eplison) for i in Y_predicted_new]
    Y_predicted_new = np.array(Y_predicted_new)
    return -np.mean(Y_true*np.log(Y_predicted_new)+(1-Y_true)*np.log(1-Y_predicted_new))

In [14]:
log_loss(Y_true, Y_predicted)

17.2696280766844

## MSE with python

In [15]:
def mse(Y_true,Y_predicted):
    total_error = 0
    for yt, yp in zip(Y_true, Y_predicted):
        total_error += (yt - yp)**2
    print("Total Error:",total_error)


    mse_value = total_error/len(Y_true)
    print("MSE:",mse_value)
    return mse_value

In [16]:
mse(Y_true,Y_predicted)

Total Error: 1.83
MSE: 0.366


0.366

## MSE with Numpy

In [17]:
mse = (np.square(Y_predicted - Y_true)).mean(axis=0)

In [18]:
mse

0.366